### ISSUE TITLE
[CSC 310] About Process Level 3

### ISSUE THREAD

**Issue by MJSher** [rhodyprog4ds/BrownFall23#15]
Hello Dr. Brown,

I know that process level 3 is different from other level 3's (one example of process level 3 I am doing is reviewing Think like a data scientist and seeing if it would be good learning material for the beginning of the semester) and I was wondering if I would need any code for my process level 3 notebook, or if the notebook can only be in markdown text form. 

Thank you,
Madison Sherlock

**Comment by brownsarahm** [comment]
process level 3 does not require code
