### ISSUE TITLE
[CSC 310] question: About German.data

### ISSUE THREAD

**Issue by MJSher** [rhodyprog4ds/BrownFall23#2]
Section 2.8 of Assignment 2 asks to read in german.data and find ways to display it more correctly. However, I am unsure how to do that because I do not know what the data represents. How can I sort this into rows and columns if I do not know how many columns there needs to be, and what labels need to be added. Would it be okay for you to explain what data German.data represents so that I will be able to fix it?
Here is the link to german.data for reference: https://github.com/rhodyprog4ds/02-python-access-fa23-MJSher/blob/main/data/german.data

**Comment by brownsarahm** [comment]
This is a great question. here is data about the [german data](http://archive.ics.uci.edu/dataset/144/statlog+german+credit+data)
