### ISSUE TITLE
[CSC 310] Question: About continuous valued variables

### ISSUE THREAD

**Issue by MJSher** [rhodyprog4ds/BrownFall23#3]
In assignment 3, the assignment talks about required datasets having some number of continuous valued variables. What do continuous valued variables mean? I tried searching the answer up but I didn't get any good responses. The reason why I am asking is because I believe knowing this will help me decide whether I would like to do a peer review or not

**Comment by brownsarahm** [comment]
this will be defined in class on Thursday and be in those notes, but it's things like height that can take on any value on a continuum (albeit within a range), rather than things like color of a stop light which takes one of 3 discrete values (red, green, yellow)

**Comment by MJSher** [comment]
Ah, okay. I'm still wondering which path I should take for this assignment
