### ISSUE TITLE
[CSC 310] Question: About the file for Assignment 4 step 4.2 

### ISSUE THREAD

**Issue by MJSher** [rhodyprog4ds/BrownFall23#4]
What file should you perform the steps for section 4.2 of assignment 4?:

"4.2. Check the Datasets you have worked with already
In the datasets you have used or come across but decided you could not work with in your past assignments identify at least one thing you could not do because the data was not in an appropriate format."

there is a potential file named cleaning_notes.md, but that is specifically for section 4.4 of assignment 4, and I do not think it also applies to 4.2, especially since 4.2 has some coding involved.

**Comment by brownsarahm** [comment]
I added a file name to the instructions, it will be visible shortly
