### ISSUE TITLE
[CSC 310] Assignment 4 question: How to turn this string into a dictionary 

### ISSUE THREAD

**Issue by MJSher** [rhodyprog4ds/BrownFall23#5]
So I was checking out the data types for my base column in pokedex.csv, and I noticed that it was a string value despite the fact that the format is very much supposed to be that of a pythonic dictionary
![image](https://github.com/rhodyprog4ds/BrownFall23/assets/90425926/273cba79-146d-4f9e-98ba-0ffc40aa0826)
I believe the reason behind this has to do with the quotation marks between the brackets. If that is the case, how can I convert this string into a proper dictionary (AKA remove the quotation marks from every instance of base) so I can be able to work with it as intended? 
Here's a snippet of what pokedex.csv looks when raw so you can better see the quotation marks: 
![image](https://github.com/rhodyprog4ds/BrownFall23/assets/90425926/511205cd-bcd6-4970-9860-3cebc54eee4a)

**Comment by brownsarahm** [comment]
we are going to work on this on problem tomorrow. 

You keep encountering challenges right before I teach them!
