### ISSUE TITLE
CSC 310 Question [Assignment 4]: dict(string) does not work on a string of a dictionary

### ISSUE THREAD

**Issue by MJSher** [rhodyprog4ds/BrownFall23#6]
Remember when I wanted to convert a string into a dictionary? Well I tried implementing dict() on the string, but it did not work: 
![image](https://github.com/rhodyprog4ds/BrownFall23/assets/90425926/c1c793d5-0dca-4a99-ab3b-d242d6037011)
When turning all of base into a dictionary as so, this happens: 
![image](https://github.com/rhodyprog4ds/BrownFall23/assets/90425926/b075c9c5-7d9d-4872-9aa2-588d0fd788b7)
As you can see, the values are the strings, but when I convert all of those values into dictionaries themselves, I get the same error: 
![image](https://github.com/rhodyprog4ds/BrownFall23/assets/90425926/0664040c-d773-44cf-b3fe-46a5cb2025b3)
I do not understand why this is resulting in an error when the strings contain everything needed for a dictionary

**Comment by brownsarahm** [comment]
this was a single string, the key here is to use string methods to operate on it.
